// <auto-generated />
using System;
using Licitaciones.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Licitaciones.Infrastructure.Migrations
{
    [DbContext(typeof(LicitacionesDbContext))]
    [Migration("20260723025035_ConvertirFechasAUtc")]
    partial class ConvertirFechasAUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Licitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminada")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PresupuestoEstimadoCRC")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodigoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_licitaciones_codigo_normalizado");

                    b.HasIndex("Eliminada");

                    b.HasIndex("Estado");

                    b.ToTable("licitaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_licitaciones_presupuesto_positivo", "\"PresupuestoEstimadoCRC\" > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.NivelAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aprobador")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoMaximoCRC")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontoMinimoCRC")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MontoMaximoCRC")
                        .IsUnique()
                        .HasDatabaseName("ix_niveles_aprobacion_unico_rango_abierto")
                        .HasFilter("\"MontoMaximoCRC\" IS NULL");

                    b.ToTable("niveles_aprobacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_niveles_aprobacion_monto_minimo_positivo", "\"MontoMinimoCRC\" > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LicitacionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoOfertadoCRC")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("LicitacionId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("ix_ofertas_licitacion_proveedor");

                    b.ToTable("ofertas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ofertas_monto_positivo", "\"MontoOfertadoCRC\" > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Eliminado");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_proveedores_nombre_normalizado");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.TipoCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CRCporUSD")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaVigencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_cambio_unico_activo")
                        .HasFilter("\"Activo\" = true");

                    b.ToTable("tipos_cambio", null, t =>
                        {
                            t.HasCheckConstraint("ck_tipos_cambio_valor_positivo", "\"CRCporUSD\" > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
                {
                    b.HasOne("Licitaciones.Domain.Entidades.Licitacion", null)
                        .WithMany()
                        .HasForeignKey("LicitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licitaciones.Domain.Entidades.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
